### ISSUE TITLE
SharpDX 2.6.3 NuGet packages different from RoomAliveToolkit packages

### ISSUE THREAD

**Issue by damianperera** [rolandsmeenk/HolographicStudio#2]
## Issue

The SharpDX 2.6.3 packages used in Holographic Studio are signed releases from NuGet. However, RoomAliveToolkit uses the same packages that are unsigned. This causes build errors where the PublicTokens of both packages conflict. 
## Suggestion

I would like to suggest that you remove the SharpDX project import in the solution, remove the NuGet references and the packages.config file, and instead reference the same SharpDX library that RoomAliveToolkit uses present in _RoomAliveToolkit\ProCamCalibration\packages\SharpDX.2.6.3\Bin\_ - the correct version will have to be referenced by developers depending on their development environment.

**Comment by rolandsmeenk** [comment]
Yes, both RoomAliveToolkit and HolographicStudio pull down the same SharpDX packages from Nuget. RoomAliveToolkit references the needed DLL's directly. In HolographicStudio I let the $(SharpDXPackageBinDir) determine which libraries to reference. This results in different libraries being referenced. I prefer using SharpDXPackageBinDir that is constructed in the SharpDX.targets file and that's why I created a pull request for RoomAliveToolkit that also uses this. However there's not been a response to that pull request yet.
